codbex/codbex-kronos

- modules/engines/engine-hdb/src/main/java/com/codbex/kronos/hdb/ds/model/hdbscalarfunction/DataStructureHDBScalarFunctionModel.java
> Fixed cast error for hdbscalarfunction

- .github/workflows/build.yml
- .github/workflows/pull-request.yaml
> Sonar configs

- pom.xml
Reverts codbex/codbex-kronos#231
> Revert "Bump jetty-servlets from 9.4.12.v20180830 to 11.0.11"

- pom.xml
Reverts codbex/codbex-kronos#232
> Revert "Bump logback.version from 1.3.0-beta0 to 1.4.0"

- modules/ide/migration/src/main/resources/META-INF/dirigible/ide-migration/migration-launch.html
- modules/ide/migration/src/main/resources/META-INF/dirigible/ide-migration/migration-perspective.html
> [IDE] Migration perspective fix

- modules/api/api-xsjs/src/main/resources/META-INF/dirigible/kronos/web/web.js
> Fixed path for incoming xsjs request

- modules/engines/engine-xsjs/src/main/java/com/codbex/kronos/engine/KronosJavascriptEngineRestService.java
- modules/engines/engine-xsjs/src/test/java/com/codbex/kronos/engine/JavascriptEngineRestServiceTest.java
> Fixed xsjs engine rest service to work with path param

- pom.xml
Reverts codbex/codbex-kronos#273
> Revert "Bump selenium-java from 4.5.0 to 4.5.3"

- samples/api-session/session-sample.xsjs
Fix the session API so it works out of the box when imported from the release zip
Closes #341
> [Samples] Fix API-Session sample

- samples/api-hdb/hdb-sample.xsjs
Fix the session API so it works out of the box when imported from the release zip
Closes #337
> [Samples] Fix API-HDB sample

- samples/api-import/import-sample.xsjs
Fix the import API so it works out of the box when imported from the release zip
Closes #338
> [Samples] Fix API-Import sample

- samples/api-hdb/hdb-sample.xsjs
- samples/api-import/import-sample.xsjs
- samples/api-session/session-sample.xsjs
Fix the following samples to work out of the box when imported from the release zip
- api-hdb
- api-import
- api-session
> [Samples] Fix HDB/Import/Session Samples

- samples/api-hdb/hdb-sample.xsjs
- samples/api-import/import-sample.xsjs
- samples/api-session/session-sample.xsjs
Fix hdb/import/session samples
> Fix HDB/Import/Session samples

- application/pom.xml
- samples/api-hdb/hdb-sample.xsjs
- samples/api-import/import-sample.xsjs
- samples/api-session/session-sample.xsjs
Added database dependencies and fix samples
> Added PSQL and HANA dependencies

- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/handler/KronosOData2EventHandler.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/handler/KronosScriptingOData2EventHandler.java
- components/engine-xsodata/src/main/resources/META-INF/services/org.eclipse.dirigible.engine.odata2.sql.api.OData2EventHandler
> #396 [XSOData] Using procedures for create/update doesn't work - DG8

- pom.xml
- releng/server/pom.xml
> Fixes #394 [XSOData] No such resource error

- pom.xml
Reverts codbex/codbex-kronos#408
> Revert "Bump logback.version from 1.2.11 to 1.4.10"

- pom.xml
**New**
**Changed**
**Removed**
> bump jackson to 2.15.2

- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/filter/XSODataForwardFilter.java
A fix for https://github.com/codbex/codbex-kronos/issues/565
> Remove double slashes from the path

- components/api-xsjs/src/main/resources/META-INF/dirigible/kronos/http/http.js
A fix for https://github.com/codbex/codbex-kronos/issues/559
> fix DELETE method

- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/filter/XSODataForwardFilter.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/synchronizer/XSODataSynchronizer.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/transformers/TableMetadataProvider.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/transformers/XSOData2ODataMTransformer.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/transformers/XSODataArtefactParser.java
- components/engine-xsodata/src/main/java/com/codbex/kronos/engine/xsodata/utils/ODataUtils.java
- components/engine-xsodata/src/test/java/com/codbex/kronos/engine/xsodata/utils/ODataUtilsTest.java
- pom.xml
Support exposing OData tables/views from another schema.
Remove the need of having synonyms for resources from different schema.
> Support exposing OData tables/views from another schema

- components/api/api-javascript/src/main/resources/META-INF/dirigible/kronos/package.json
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/package.json
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/project.json
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/src/run.mjs
- pom.xml
- use latest abap dependencies
- extract method in run.mjs to be easier to call it from another TS file
- send empty params to show how to properly pass params to the ABAP code since it not so intuitive 
- update project.json to transpiler ts code as well
- update Kronos ABAP API dependenices
> Update ABAP template

- components/api/api-javascript/src/main/resources/META-INF/dirigible/kronos/src/js/abap/database.ts
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/abaplint.json
Implementation for issue https://github.com/codbex/codbex-kronos/issues/639
Example usage:
- To configure `DefaultDB`
```
DatabaseInitializer.initDefaultDataSource();
```
- To configure custom data source, for example data source with name `ANOTHER_DS`
```
DatabaseInitializer.initDefaultDataSource("ANOTHER_DS");
```
The change is backward compatible.
> Configurable ABAP datasource

- application/pom.xml
- pom.xml
- use dirigible-components-group-database only
- cleanup
> include all supported databases

- pom.xml
> Platform parent v1.0.42

- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/abaplint.json
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/build-linux.sh
- components/template-abap/src/main/resources/META-INF/dirigible/template-abap/build-mac.sh
Enhance ABAP template
- make it easier for ABAP code development based on the experience we had
> Enhance ABAP starter template

- application/src/test/java/com/codbex/kronos/engine/api/test/KronosSuiteTest.java
**New**
**Changed**
**Removed**
> cleanup KronosSuiteTest.java

- pom.xml
**New**
**Changed**
**Removed**
> parent 11.31.0

- integration-tests/src/test/java/com/codbex/kronos/integration/tests/ABAPStarterTemplateIT.java
- integration-tests/src/test/java/com/codbex/kronos/integration/tests/HomePageIT.java
- integration-tests/src/test/java/com/codbex/kronos/integration/tests/KronosIntegrationTest.java
- pom.xml
**New**
**Changed**
**Removed**
> parent 11.35.0

- pom.xml
**New**
**Changed**
**Removed**
> Parent 11.44.0

- application/Dockerfile
Copy "oras-artifacts" to the dedicated folder "/codbex" to allow mounting the target folder.
> copy "oras-artifacts" to the dedicated folder "/codbex"
